# Generated by Django 5.0.4 on 2024-04-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
