# Generated by Django 5.0.4 on 2024-04-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
    ]
